# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybideo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
