# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybideo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie_data',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='image_path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Movie_data',
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybideo.Movie'),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='movie_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybideo.MovieGenre'),
        ),
    ]
